version: "3.8"

services:
  rails-sandbox:
    build:
      context: .
      dockerfile: Dockerfile.dev # Dockerfile.dev を指定
    volumes:
      - ".:/rails" # ローカルのファイルとコンテナ内のファイルを共有
    ports:
      - "3001:3000"
    environment:
      - RAILS_ENV=development
    command: ["bin/rails", "server", "-b", "0.0.0.0"]
